services:
    dsnet_security.panel_resource_owner:
        class: Dsnet\SecurityBundle\Services\PanelResourceOwner
        arguments: ["@buzz", "@router", "%dsnet_security.config%"]

    dsnet_security.security.authentication.provider:
        class: Dsnet\SecurityBundle\Security\Authentication\Provider\OAuthProvider
        arguments: ["", "@dsnet_security.panel_resource_owner", "@doctrine.orm.default_entity_manager"]

    dsnet_security.security.authentication.listener:
        class: Dsnet\SecurityBundle\Security\Firewall\OAuthListener
        arguments: ["@security.context", "@security.authentication.manager", "@dsnet_security.panel_resource_owner", "@session.flash_bag"]
