<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Media;
use Doctrine\ORM\EntityRepository;

/**
 * MediaRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends EntityRepository
{
    public function increasePopularity(Media $media)
    {
        $this->getEntityManager()->createQuery(
            'UPDATE AppBundle:Media m SET m.popularity = m.popularity + 1 WHERE m.id = :id'
        )
            ->setParameter('id', $media->getId())
            ->execute();
    }
}
